// Generated by scripts/base-rates.ts from /v1/cryptocurrency/listings/historical.
// Do not edit by hand.
export const BASE_RATES = {
  "months": 6,
  "generatedAt": "2026-09-25T16:39:21.741Z",
  "snapshots": [
    "2025-10-01",
    "2025-11-01",
    "2025-12-01",
    "2026-01-01",
    "2026-02-01",
    "2026-03-01"
  ],
  "buckets": [
    {
      "from": 1,
      "to": 10,
      "samples": 60,
      "stayed": 53
    },
    {
      "from": 11,
      "to": 50,
      "samples": 240,
      "stayed": 206
    },
    {
      "from": 51,
      "to": 100,
      "samples": 300,
      "stayed": 215
    },
    {
      "from": 101,
      "to": 200,
      "samples": 600,
      "stayed": 430
    },
    {
      "from": 201,
      "to": 300,
      "samples": 600,
      "stayed": 372
    },
    {
      "from": 301,
      "to": 500,
      "samples": 1200,
      "stayed": 508
    },
    {
      "from": 501,
      "to": 1000,
      "samples": 3000,
      "stayed": 1750
    }
  ]
} as {
  months: number;
  generatedAt: string | null;
  snapshots: string[];
  buckets: Array<{ from: number; to: number; samples: number; stayed: number }>;
};
