// Generated by scripts/base-rates.ts from /v1/cryptocurrency/listings/historical.
// Empty until that script runs with a Startup-plan key.
export const BASE_RATES = {
  "months": 12,
  "generatedAt": null as string | null,
  "snapshots": [] as string[],
  "buckets": [] as Array<{ from: number; to: number; samples: number; stayedTop500: number }>
};
