// Precompute base rates from CMC historical listings. Needs a Startup-plan key.
//   bun scripts/base-rates.ts
// Writes lib/baseRatesData.ts. Cost: ~10 credits per snapshot (limit 1000), 1 snapshot per quarter.

import { writeFileSync } from "node:fs";

const KEY = process.env.CMC_API_KEY;
if (!KEY) throw new Error("Set CMC_API_KEY in .env");

const MONTHS_AHEAD = 12;
const BUCKETS = [
  [1, 10],
  [11, 50],
  [51, 100],
  [101, 200],
  [201, 300],
  [301, 500],
  [501, 1000],
] as const;

// Quarterly snapshots from Jan 2020 until 12 months before today.
function snapshotDates(): string[] {
  const out: string[] = [];
  const last = new Date();
  last.setUTCMonth(last.getUTCMonth() - MONTHS_AHEAD);
  for (let d = new Date(Date.UTC(2020, 0, 1)); d <= last; d.setUTCMonth(d.getUTCMonth() + 3)) {
    out.push(d.toISOString().slice(0, 10));
  }
  return out;
}

function plus(date: string, months: number) {
  const d = new Date(`${date}T00:00:00Z`);
  d.setUTCMonth(d.getUTCMonth() + months);
  return d.toISOString().slice(0, 10);
}

const cache = new Map<string, Map<number, number>>();

async function ranksOn(date: string): Promise<Map<number, number>> {
  const hit = cache.get(date);
  if (hit) return hit;
  const url = `https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/historical?date=${date}&limit=1000&convert=USD`;
  const res = await fetch(url, { headers: { "X-CMC_PRO_API_KEY": KEY!, Accept: "application/json" } });
  const body = (await res.json()) as { status: { error_code: number; error_message?: string; credit_count?: number }; data?: Array<{ id: number; cmc_rank: number }> };
  if (!res.ok || body.status.error_code) throw new Error(`${date}: HTTP ${res.status} ${body.status.error_message}`);
  console.log(`${date}: ${body.data?.length} coins, ${body.status.credit_count} credits`);
  const ranks = new Map((body.data ?? []).map((c) => [c.id, c.cmc_rank]));
  cache.set(date, ranks);
  await new Promise((r) => setTimeout(r, 2500)); // stay under 30 requests/minute
  return ranks;
}

const dates = snapshotDates();
const counts = BUCKETS.map(([from, to]) => ({ from, to, samples: 0, stayedTop500: 0 }));

for (const date of dates) {
  const then = await ranksOn(date);
  const later = await ranksOn(plus(date, MONTHS_AHEAD));
  for (const [id, rank] of then) {
    const b = counts.find((x) => rank >= x.from && rank <= x.to);
    if (!b) continue;
    b.samples++;
    const r = later.get(id);
    if (r !== undefined && r <= 500) b.stayedTop500++;
  }
}

const data = { months: MONTHS_AHEAD, generatedAt: new Date().toISOString(), snapshots: dates, buckets: counts };
writeFileSync(
  new URL("../lib/baseRatesData.ts", import.meta.url),
  `// Generated by scripts/base-rates.ts from /v1/cryptocurrency/listings/historical.\n// Do not edit by hand.\nexport const BASE_RATES = ${JSON.stringify(data, null, 2)} as {\n  months: number;\n  generatedAt: string | null;\n  snapshots: string[];\n  buckets: Array<{ from: number; to: number; samples: number; stayedTop500: number }>;\n};\n`,
);
console.table(counts.map((b) => ({ ...b, rate: `${Math.round((b.stayedTop500 / b.samples) * 100)}%` })));
